name: ci-main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest
        node: [16]

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.5

      - name: Cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/pnpm-lock.yaml')) }}

      - name: Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm

      - name: Lint
        run: pnpm lint

      - name: Coverage
        uses: codecov/codecov-action@v1

      - name: Build
        run: pnpm build

      - name: Version Check
        id: check
        uses: EndBug/version-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        if: github.event_name == 'push' && steps.check.outputs.changed == 'true'
        run: ./scripts/release.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
